CREATE DATABASE QLNV
GO
USE QLNV
GO

CREATE TABLE NhanVien
(
	MaNV CHAR(5) CONSTRAINT PK_MaNV PRIMARY KEY NOT NULL,
	TenNV NVARCHAR(20),
	NgaySinh DATE,
	GioiTinh BIT,
	SoDT INT,
	MaPB CHAR(10) CONSTRAINT FK_MaPB FOREIGN KEY REFERENCES PhongBan(MaPB) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	Picture VARCHAR(15),
)


CREATE TABLE PhongBan
(
	MaPB CHAR(10) CONSTRAINT PK_MaPB PRIMARY KEY NOT NULL,
	TenPB NVARCHAR(20),
)

INSERT PhongBan
VALUES('HC', N'Hành chính')
INSERT PhongBan
VALUES('KT', N'Kế toán')
INSERT PhongBan
VALUES('NS', N'Nhân sự')

INSERT NhanVien
VALUES('01', 'Tran Cao Duyen', '02/12/2001', '1', '02932423', 'KT' ,NULL)
INSERT NhanVien
VALUES('02', 'Pham Ngoc Thai', '05/09/2003', '1', '02932882', 'HC' ,NULL)
INSERT NhanVien
VALUES('03', 'Tran Thai Cong', '06/30/2002', '1', '02325325', 'NS' ,NULL)
INSERT NhanVien
VALUES('04', 'Nguyen Yen Linh', '05/20/2002', '0', '02923523', 'HC' ,NULL)